[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100

[build.nixpacks]
aptPackages = ["postgresql-client"]

# Railway specific configurations
[variables]
NODE_ENV = "production"